### ISSUE TITLE
building Dwarf Therapist fails on slackware-current i686 

### ISSUE THREAD

**Issue by DeDeRon** [McArcady/lnp-forge#1]
see attached build log, happens when building the doc pdf file. i usually disable building the documentation.

[build.log.dt.txt](https://github.com/McArcady/lnp-forge/files/229952/build.log.dt.txt)

**Comment by McArcady** [comment]
is it  possible to deactivate the target 'manual' without patching the .pro file?

**Comment by DeDeRon** [comment]
Sorry, i can't help. Now I remember why i never came across this issue before: I didn't have tex installed, so this step was always skipped. But not now anymore.

I'd ask in the bay12 forums in the Dwarf Therapist thread.

**Comment by DeDeRon** [comment]
I investigated some more. The problem here is that slackware uses tetex instead of texlive. the reason is that texlive if huge. tetex itself is not maintained anymore. so the problem will probably occur on slackware only. i'm not familiar with tex, so i can't send a patch to the dwarf therapist maintainers.

**Comment by McArcady** [comment]
Ok thanks for the investigation. I will make a patch to disable target 'manual'

**Comment by McArcady** [comment]
fixed in 25b3735ad60
