### ISSUE TITLE
Hey there, could you host the LinuxDwarfPack-0.47.04-r2 (DFHack-r1) here on github?

### ISSUE THREAD

**Issue by clinodev** [McArcady/lnp-forge#10]
With the DFFD being down so much the last couple weeks, a backup mirror would be great to have!

**Comment by totalbajor** [comment]
I'm looking for links myself. Let me know if you found out something.

**Comment by McArcady** [comment]
Good idea! Here it is:
[https://github.com/McArcady/lnp-forge/releases/tag/0.47.04-r2](url)
