### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by totalbajor** [McArcady/lnp-forge#11]
Missing dependencies for therapist and dfhack in order to build on Ubuntu-20.04: 
ninja-build qt5-qmake qttools5-dev-tools qt5-default libqt5svg5-dev qt5-image-formats-plugins qtbase5-dev qtdeclarative5-dev
dependencies that fixed tkinter error:
python-tk python3-tk
Also on Ubuntu-20.04 theres no packages for qt4. Installing qt5 packages listed above fixed errors.

**Comment by McArcady** [comment]
Added to the wiki - thanks for the test.
