### ISSUE TITLE
Cannot fetch dwarf fortress executable from bay12games.com

### ISSUE THREAD

**Issue by corollari** [McArcady/lnp-forge#13]
Trying to fetch the archive from http://www.bay12games.com/dwarves/df_47_04_linux.tar.bz2 with `wget` (as it is done when running the build script) results in the following errors:
```
ERROR: The certificate of 'www.bay12games.com' is not trusted.
ERROR: The certificate of 'www.bay12games.com' has expired.
```

This is pretty weird because when you access www.bay12games.com using any browser the certificate is reported to be valid, but, after some digging, it seems that the root of trust for the bay12game.com certificate is the following:
USERTrust RSA Certification Authority (Root) -> Sectigo RSA Domain Validation Secure Server CA (Intermediate) ->  Certificate on www.bay12games.com

And, while the certificates of both Certigo and bay12games.com are still valid, the USERTrust certificate expired on May 30th, thus breaking the root of trust, which I believe is what causes the problem.

**Comment by McArcady** [comment]
Thanks for reporting!
Probably related to the recent change of server ?

As a temporary workaround, it is possible to download the archive by hand and put it here:
`.build/tarballs/df_47_04_linux.tar.bz2
`
(.build/tarballs is the cache directory for downloads of lnp-forge)

**Comment by corollari** [comment]
> As a temporary workaround, it is possible to download the archive by hand and put it here:
.build/tarballs/df_47_04_linux.tar.bz2
(.build/tarballs is the cache directory for downloads of lnp-forge)

I ended up "fixing" it that way, I've also been thinking of a better fix and, looking at wget docs, the only solution I've come up with are using the --no-check-certificate flag or switching to a mirror, any ideas?

**Comment by McArcady** [comment]
I'm a bit reluctant to add the --no-check-certificate option in the scripts: even if it's probably not dangerous in this specific case (as suggested by the fact that browsers ignore the error), it may be for other packages.
We should use the workaround for the weeks to come, and check later if the certificate issue has been resolved server-side.

**Comment by McArcady** [comment]
No more certificate problem from the server
