### ISSUE TITLE
[Suggestion] Splitting the dependencies

### ISSUE THREAD

**Issue by corollari** [McArcady/lnp-forge#17]
At the moment, the dependencies listed on the wiki are the ones needed to build the pack, whereas I expect that most users will just want to use a precompiled version of the pack instead of building it by themselves and, therefore, will not need to install the majority of the dependencies. Thus, it may make sense to split the current list of dependencies into two: one for users and another for developers, what are your thoughts on this?

I'd also like to suggest moving the wiki page to a normal file that is part of the repository, as that would allow external contributors like me to make pull requests against it.

**Comment by McArcady** [comment]
Thanks for the suggestions!
I agree completely, and will have a look at it next week.

Looking at the github help pages, it turns out that the wiki files may be cloned in their own repository:
`$ git clone https://github.com/McArcady/lnp-forge.wiki`
Pull requests may be created in this repo.

**Comment by corollari** [comment]
Could you add more details or point to some docs that explain how to create Pull requests on a wiki repository? As far as I know, the wiki repo is pretty much a simple git repo, without many of the extra features added by github on top of basic git, thus making it impossible to make pull requests against it.

Sources: 
- https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github
- https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html
- https://github.community/t/how-to-fork-a-wiki-and-send-a-pr/2006/2

**Comment by McArcady** [comment]
If you want I could make you a collaborator of lnp-forge ? This should give you write access to the wiki.
Meanwhile i've added a new page to split the build dependencies and the dependencies of the pack itself.

**Comment by McArcady** [comment]
The wiki is now editable by anyone with a github account.

**Comment by corollari** [comment]
Great!
