### ISSUE TITLE
building soundsense fails on slackware-current i686

### ISSUE THREAD

**Issue by DeDeRon** [McArcady/lnp-forge#2]
this is the build log after i disabled dwarf therapist (see issue 1) and rerun the build.

seems that "build_dir" in lib/0.0.1/scripts/build/soundsense.sh is not set.

[build.log.ss.txt](https://github.com/McArcady/lnp-forge/files/229956/build.log.ss.txt)

**Comment by McArcady** [comment]
fixed in 0355075
