### ISSUE TITLE
Evolution: provide an appimage workflow

### ISSUE THREAD

**Issue by McArcady** [McArcady/lnp-forge#20]

**Comment by McArcady** [comment]
- [x] add option and build instructions to generate the appimage package format
- [ ] add the corresponding workflow for nightly build
- [ ] test on a recent Ubuntu
- [ ] test on a recent Debian
- [ ] test on a recent Fedora/Redhat
- [ ] test on a recent Arch

**Comment by McArcady** [comment]
The AppImage generation on the github CI fails for the time being because of [this](https://github.com/linuxdeploy/linuxdeploy/issues/142) problem with linuxdeploy.
But tt's being worked on by the maintainer!

**Comment by McArcady** [comment]
The AppImage generation workflow is fixed.

**Comment by thiras** [comment]
It doesn't work on up-to-date Ubuntu 20.04

Here is the logs;

```
Starting LinuxDwarfPack-0.47.04-r3-x86_64
- configuration and game saves are stored in /home/thiras/.lnp/
- feedback or issues? see http://www.bay12forums.com/smf/index.php?topic=157712
- created with lnp-forge: https://github.com/McArcady/lnp-forge

Creating overlay of /home/thiras/.lnp/ and /tmp/.mount_LinuxDXVA0Oo in /tmp/lnp-I3Gdzc...
/tmp/.mount_LinuxDXVA0Oo/AppRun: 23: unionfs: not found
/tmp/.mount_LinuxDXVA0Oo/AppRun: 26: ./startlnp.sh: not found
fusermount: entry for /tmp/lnp-I3Gdzc not found in /etc/mtab
/tmp/lnp-I3Gdzc unmounted.
```

**Comment by McArcady** [comment]
@thiras it looks like you need package unionfs or unionfs-fuse.
I've added some checking in the script to detect this problem.

**Comment by McArcady** [comment]
For Ubuntu/Debian users, there is a .deb package available [here](https://github.com/McArcady/lnp-forge/actions/runs/251711544).
Packages for other distros are also available, but not tested yet.

**Comment by McArcady** [comment]
AppImage has been tested and reported ok on all kind of distros (except RedHat)
