### ISSUE TITLE
Pre-made Docker container

### ISSUE THREAD

**Issue by Avamander** [McArcady/lnp-forge#21]
It would be really nice if the pack would be shipped in a Docker container.

It would make it much less hassle to make sure all the dependencies exist and so on. Would also make it much more distribution agnostic.

**Comment by McArcady** [comment]
Thanks for the feedback.
I'm currently working on a AppImage release format. Starting from there we could add a docker version. 

I don't have much experience with both formats, but I'm concerned that they introduce the following problem:
after installing a new version, how will the player import its old fortress?
How will we point to the old save files without manually mounting the file system of the old container/appimage?

**Comment by Avamander** [comment]
> How will we point to the old save files without manually mounting the file system of the old container/appimage?

Use XDG base directory for configuration and mount that into the container automatically.

**Comment by McArcady** [comment]
We now provide debian, arch, rpm packages with clean user-data and dependency management.
That's still a good idea but I will close this until many people request a docker version or someone provides a patch for it.
