### ISSUE TITLE
Building dfhack failed, cannot find -lz

### ISSUE THREAD

**Issue by azycat** [McArcady/lnp-forge#22]
[build.log](https://github.com/McArcady/lnp-forge/files/4890386/build.log)
I'm trying to build lnp-forge on i386 Debian 10 Buster. I have installed all of the recommended build dependencies EXCEPT for lib32z1-dev, which is what I suspect is causing the problem. However, that package isn't available for i386. I tried installing libz1/zlib1g instead, Google said it's the multiarch equivalent, but it's still returning this error. 

Thank you very much in advance. I hope you can help me out, I'm very excited to play Dwarf Fortress!!!

**Comment by McArcady** [comment]
It sounds like an issue with the packages of 32-bits Debian: maybe try installing zlib1g-dev instead?
As far as I know lnp-forge has never been used on a pure 32-bits system, and I don't have one here. Let me know if you manage to   build all the components!
