### ISSUE TITLE
[ERROR]      ../plugins/twbt/png++/png.hpp:34:10: fatal error: png.h: No such file or directory

### ISSUE THREAD

**Issue by fundsan** [McArcady/lnp-forge#23]
[build.log](https://github.com/McArcady/lnp-forge/files/4913417/build.log)

**Comment by McArcady** [comment]
Missing pkg libpng-dev ?

**Comment by McArcady** [comment]
@fundsan: did package libpng-dev solve your build problem ?

**Comment by fundsan** [comment]
Yes it did! thank you!
