### ISSUE TITLE
Hidden dependancy python-tk

### ISSUE THREAD

**Issue by Persola** [McArcady/lnp-forge#26]
I'm on Ubuntu (18.04.4) and though I installed the dependencies recommended in the wiki while trying to launch I got:
```
WARNING: JSONConfiguration: File PyLNP.user does not exist
['Traceback (most recent call last):\n', '  File "launch.py", line 12, in <module>\n    lnp.PyLNP()\n', '  File "[REDACTED]/lnp-forge-master/.build/src/lnp-0.14a/core/lnp.py", line 119, in __init__\n    self.initialize_ui()\n', '  File "[REDACTED]/lnp-forge-master/.build/src/lnp-0.14a/core/lnp.py", line 211, in initialize_ui\n    from tkgui.tkgui import TkGui\n', '  File "tkgui/tkgui.py", line 16, in <module>\n    from . import controls, binding\n', '  File "tkgui/controls.py", line 11, in <module>\n    from . import binding\n', '  File "tkgui/binding.py", line 18, in <module>\n    from Tkinter import END\n', '  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>\n    raise ImportError, str(msg) + \', please install the python-tk package\'\n', 'ImportError: No module named _tkinter, please install the python-tk package\n']
```

If you reformat that you can see it's asking me to install `python-tk`, and doing that seemed to solve the problem. Needs to be added to the Ubuntu/Debian dependency list?

While I'm here, a couple ease of use issues:
1. I jumped right into the usage instructions and started installing packages one by one because I didn't realize a list was provided. My fault for not reading the whole README first but maybe mention it in the usage instructions just to make it more obvious.
2. (I'm not an experienced DF player) I didn't really get what you meant in the last line of the instructions where you say, 'The pack is ready to use in...'. For example I wouldn't know if I'm supposed to start DF and run this at the same time or if it'll launch it for me, etc. (I think I get that now so no need to explain). I navigated to that folder and tried to read the README in _there_, but it was broken looking for a doc file that didn't exist, so I tried reading the raw doc files and ended up reading what I now realize is the README for PyLNP. (Aside: that file, at least in its raw form, says 'There's not much to it:  run the launcher (see below)' and then goes on to say nothing else about running any launcher 😆) So I figured I should just try to launch it, but there was both a `startlnp.sh` and a `launch.py` so I wasn't sure which to run. I tried one and got the error above, so I was still unsure if I was supposed to be running it directly until I tried installing python-tk. Which is all just to say I think you should try to be more explicit about exactly you do to use the project to help out the titular newb.

If you take contributions I'd be happy to reformat some of these suggestions as a PR.

**Comment by Persola** [comment]
I just saw in another issue that you may not have had testers on Ubuntu yet, so for the record after installing `python-tk` I believe it worked OK. I'm not able to play the game yet due to trouble configuring a terminal in (as I understand it) the underlying LNP GUI, but I had this same problem a few minutes ago with LinuxLNP so I imagine it's not related to lnp-forge.

By the way, are lnp-forge and LinuxDwarfPack the same thing?

**Comment by McArcady** [comment]
`LinuxDwarfPack` is the name of a pre-built starter pack shared on [dffd](https://dffd.bay12games.com/who.php?id=7393) (DFFD being the server that hosts downloads for most DF-related stuff). Most people use this pre-built pack, and the instructions on how to start it are actually available in the download description.
lnp-forge is the name of the utility that helps build the pack, most people do not need it directly.

I think the dependency `python-tk` is only required if python2 is set as default on your distro. The maintainer of the PyLNP GUI now recommends using python3 by default, though AFAIK it works with both.
One solution would be that I make python3 mandatory and adapt the script `startlnp.sh` to enforce it.

To solve your problem with the terminal configuration, you can try installing the `xterm` package, then select it in the menu 'configure terminal'.

**Comment by corollari** [comment]
> now recommends using python3 by default, though AFAIK it works with both.

I previously tried running it using python2 and ran into some problems, althought I'm not sure if that was caused by something on my system as I just immediately switched to python3, just providing a data point here.

> To solve your problem with the terminal configuration, you can try installing the xterm package, then select it in the menu 'configure terminal'.

If you'd rather avoid installing another package you can set the terminal command to be `nohup gnome-terminal -x` as long as you are using GNOME.
