### ISSUE TITLE
Build failed in step 'Retrieving needed components' tarballs'

### ISSUE THREAD

**Issue by DrYogurt** [McArcady/lnp-forge#27]
[build.log](https://github.com/McArcady/lnp-forge/files/5011266/build.log)
It seems the raw data isn't being retrieved? any idea why this might not be working. Thanks.

**Comment by corollari** [comment]
Seems like the file that is being pointed to was recently renamed (~3 hours ago) in [this commit](https://github.com/Lazy-Newb-Pack/LNP-shared-core/commit/b70208c48f0744e1135f1bc4b4bf6c0df477a47c#diff-6d82ff0c1443c531bc96483dc1731467) thus breaking the build

**Comment by DrYogurt** [comment]
> Seems like the file that is being pointed to was recently renamed (~3 hours ago) in [this commit](https://github.com/Lazy-Newb-Pack/LNP-shared-core/commit/b70208c48f0744e1135f1bc4b4bf6c0df477a47c#diff-6d82ff0c1443c531bc96483dc1731467) thus breaking the build

orry, I'm a little bit of a noob when it comes to this stuff. How should I remedy this issue?

**Comment by corollari** [comment]
I've just fixed it in #28. You can either wait for it to get merged or just build the package out of my [fork](https://github.com/corollari/lnp-forge).

**Comment by DrYogurt** [comment]
So, the keybindings issue is solved, but now I'm getting a new issue (using @corollari 's fixes)
[build.log](https://github.com/McArcady/lnp-forge/files/5011404/build.log)
 Seems to be an issue with the header files for dfhack? Thanks again

**Comment by corollari** [comment]
Seems like linking is failing because it can't find the SDL library, could you check if you have it installed?

**Comment by DrYogurt** [comment]
> Seems like linking is failing because it can't find the SDL library, could you check if you have it installed? If so I'd suggest running the ld command with the --verbose flag to see how it is trying to access the library.

Not sure what you're referring to by 'ld' command. I do seem to have sdl installed (libsdl2).

**Comment by corollari** [comment]
What OS are you using?

**Comment by DrYogurt** [comment]
(Using Pop! OS) Well, it seems I was missing one of the sdl files, but now I'm having a different issue.
[build.log](https://github.com/McArcady/lnp-forge/files/5011446/build.log)
Is this another dependency problem?

**Comment by DrYogurt** [comment]
[build.log](https://github.com/McArcady/lnp-forge/files/5011465/build.log)
New test, new issue!
It now seems to be failing at the appimage creation step :/. Thanks again for all the help @corollari

**Comment by corollari** [comment]
I don't have much experience with the app image stuff, so I don't think I can be of much help here, maybe @McArcady has better insights.

For anyone reading this the error seems to be:
```
[appimage/stderr] /usr/bin/appstreamcli: symbol lookup error: /lib/x86_64-linux-gnu/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
```

**Comment by corollari** [comment]
You can also remove the AppImage step if that's something that you don't need. Alternatively, if you aren't modifying any of the source code you could just download the built AppImage from [this CI run](https://github.com/McArcady/lnp-forge/actions/runs/191567431)

**Comment by McArcady** [comment]
The symbol lookup error is probably due to the fact that the tool 'linuxdeploy' (downloaded by lnp-forge) is an appimage itself, and has specific dependencies that are not met on your system.
Since this problem does not happen on the github CI, I suggest we don't investigate further. Just deactivate the 'AppImage' step in menuconfig.
Thanks for the report and the PR!
