### ISSUE TITLE
Arch-Linux / Manjaro dependencies

### ISSUE THREAD

**Issue by Hufschmidt** [McArcady/lnp-forge#38]
Hi,

had to change dependencies in Arch-Linux package to the following to be able to install the package:

depend = sdl_image
depend = sdl_ttf
depend = gnome-terminal
depend = jre8-openjdk
depend = tk
depend = qt5-base
depend = unionfs-fuse

**Comment by McArcady** [comment]
Thanks for the report.
Indeed the python3 dependency seems to not exist in the AUR.
I will replace it with "python", which should install python3 by default on Arch.

**Comment by McArcady** [comment]
Next build [here](https://github.com/McArcady/lnp-forge/actions/runs/444592297) should have the problem fixed.
