### ISSUE TITLE
Additional build dependencies needed for Fedora

### ISSUE THREAD

**Issue by rkraneis** [McArcady/lnp-forge#42]
I am building lnp-forge in a Fedora toolbox and had to install the following additional dependencies (besides those given in the wiki) to be able to successfully run configure:
- bison
- flex
- patch
- libtool
- SDL_image
- SDL_ttf

df_hack additionaly requires
- libpng-devel (twbt)
- SDL-devel (stonesense)

(so I guess those should be added to configure)

**Comment by rkraneis** [comment]
Additionally, to get rid of
> WARNING: No PIL support available - cannot perform image manipulation

when starting lnp
- python3-pillow-tk

is required. (I have no idea if that is relevant, though.)

**Comment by McArcady** [comment]
Thanks for reporting! 
python3-pillow-tk has been added to the RPM package dependencies.
The configure/build dependencies will require a bit more work to be included in the scripts.

**Comment by McArcady** [comment]
Missing build deps added to the wiki as well
