### ISSUE TITLE
Build fails for Archlinux/Manjaro and Appimage [SOLVED]

### ISSUE THREAD

**Issue by Linuxious** [McArcady/lnp-forge#45]
As the title says I keep getting this error on the build:

[INFO ]    Building arch-
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building arch-'
[ERROR]  >>        called in step 'Building components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@261]
[ERROR]  >>        called from: do_fpm_build[scripts/build/fpm.sh@59]
[ERROR]  >>        called from: do_arch_build[scripts/build/arch.sh@26]
[ERROR]  >>        called from: main[scripts/lnp-forge.sh@631]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '@@CT_DOCDIR@@/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 13:30.25)
make: *** [bin/lnp-forge:151: build] Error 127

**Comment by McArcady** [comment]
A build dependency may be missing, could you attach your `build.log` ?

**Comment by Linuxious** [comment]
Sure! 
[build.log](https://github.com/McArcady/lnp-forge/files/6176392/build.log)

**Comment by McArcady** [comment]
try installing ruby the the ruby gem "fpm", required for packaging
`gem install --no-document fpm`

**Comment by Linuxious** [comment]
Unfortunately it still does not work

**Comment by McArcady** [comment]
maybe fpm is not installed in /usr/local/bin on your distro, could you try:
`$ type fpm`

**Comment by Linuxious** [comment]
type fpm:
"fpm is /usr/bin/fpm"

just linked fpm to /usr/local/bin and it works thanks!

**Comment by Linuxious** [comment]
So now the Appimage is failing to build

**Comment by McArcady** [comment]
Thanks for the report, I fixed the use of fpm so that is should depend on the distro
