### ISSUE TITLE
Something is wrong with Meph raws

### ISSUE THREAD

**Issue by Xerkus** [McArcady/lnp-forge#51]
On fresh new install of 0.47.05-r2 after I changed graphics to Meph  materials become all messed up. Pretty much all non-ore stone is now in economic category, eg on new embark I can't make blocks or build furnaces from Periclase. Other Stone category contains carpets and other seemingly unrelated stuff.

Meph modpack new workshops also appeared in game.

it looks like wrong, full version, was used that changes the raws and potentially changes it only halfway since other bits of meph pack are not there.

**Comment by McArcady** [comment]
Indeed it comes from my own fork of DFGraphics and has not been updated for a while...
Meanwhile I discovered an up-to-date repo by jecowa here: https://github.com/DFgraphics/Meph
-> will have to adapt the scripts to fetch the graphic-pack from there in the future

**Comment by Xerkus** [comment]
FYI

I've replaced Meph in this release with https://github.com/DFgraphics/Meph/releases/tag/47.05_v5.5.1-V and encountered hard crashes with twbt.
So far narrowed it down to `_Meph_variety.png` tileset override. Commenting it out in overrides https://github.com/DFgraphics/Meph/blob/50b5443dd65bd1000bdaaaff03ec8e98590a6c87/data/init/overrides.txt#L35 prevents crashes from, what i figured, is an attempt to render vermin remains.

```
Stack trace of thread 23478:
#0  0x00007ffff62d32a2 raise (libc.so.6 + 0x3d2a2)
#1  0x00007ffff62bc8a4 abort (libc.so.6 + 0x268a4)
#2  0x00007ffff6862a46 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold (libstdc++.so.6 + 0xa1a46)
#3  0x00007ffff686e29c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xad29c)
#4  0x00007ffff686e307 _ZSt9terminatev (libstdc++.so.6 + 0xad307)
#5  0x00007ffff686e5a9 __cxa_throw (libstdc++.so.6 + 0xad5a9)
#6  0x00007fff5ccc4298 _ZN13renderer_cool15update_map_tileEii (twbt.plug.so + 0x28298)
#7  0x00007fff5ccc6afd _ZN13renderer_cool11display_mapEv (twbt.plug.so + 0x2aafd)
#8  0x00007fff5ccc8eeb _ZN13renderer_cool4drawEi (twbt.plug.so + 0x2ceeb)
#9  0x00007ffff6a2c6b0 _ZN15renderer_opengl6renderEv (libgraphics.so + 0x4c6b0)
#10 0x00007ffff6a29a88 _ZN9enablerst8do_frameEv (libgraphics.so + 0x49a88)
#11 0x00007ffff6a29f71 _ZN9enablerst13eventLoop_SDLEv (libgraphics.so + 0x49f71)
#12 0x00007ffff6a2a6f2 _ZN9enablerst4loopESs (libgraphics.so + 0x4a6f2)
#13 0x00007ffff6a25326 main (libgraphics.so + 0x45326)
#14 0x00007ffff62bdb75 __libc_start_main (libc.so.6 + 0x27b75)
#15 0x000000000040970f n/a (Dwarf_Fortress + 0x970f)
```

I do not know what is the cause here. I've put the save aside and I will try to reproduce and narrow the problem when/if I get time for that.

Letting you know in case there are some compat issues.

**Comment by Xerkus** [comment]
Huh, Meph pack changelog:

> 10/12/2020 - V1.3 - updated to DFHack 0.47.04-r3, reverted TWBT plugin back to -r1 due to vermin remains bug (very experimental - if you encounter problems/CTDs port your save back to V1.2 please)
>
> 03/07/2021 V1.4 - updated DF to 0.470.5, updated to DFHack 0.47.05-r1, added new TWBT 0.47.05r1 version of thurin to solve the vermin bug (thanks!), updated DwarfTherapist to support 0.47.05 (there may be a minor update to the toolsets later to align it with LNP, but this should not brake saves)

**Comment by McArcady** [comment]
The graphics have been updated and the pack now applies the workaroung you've found for Meph pack.
The result is available [here](https://github.com/McArcady/lnp-forge/actions/runs/828049714) if you'd like to give it a try.

**Comment by McArcady** [comment]
The graphics have been updated, and TwbT now includes the fix for Meph.
There is a build of the new pack [here](https://github.com/McArcady/lnp-forge/actions/runs/829350899), if you want to give it a try.
