### ISSUE TITLE
Build fails extracting and patching components CT_DoExecLog

### ISSUE THREAD

**Issue by smurkcs** [McArcady/lnp-forge#52]
Hey there - I'm getting this error each time I try to build...
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Extracting and patching components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@261]
[ERROR]  >>        called from: do_kloker_extract[scripts/build/kloker.sh@33]
[ERROR]  >>        called from: main[scripts/lnp-forge.sh@608]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '@@CT_DOCDIR@@/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 0:02.38)
make: *** [bin/lnp-forge:151: build] Error 127

attached build.log 
[build.log](https://github.com/McArcady/lnp-forge/files/6636574/build.log)

**Comment by McArcady** [comment]
Try again after installing package rsync

**Comment by smurkcs** [comment]
installing rsync fixed my issue. thanks!
