### ISSUE TITLE
Cannot start on Fedora 34

### ISSUE THREAD

**Issue by schemar** [McArcady/lnp-forge#54]
I cannot get the linux-dwarf-pack to start as expected.

What I tried:

1. Downloading and running the `AppImage` file from the latest release
2. Downloading and `sudo dnf install`ing the `.rpm` packe from the latest release

Error in both cases:

```
Missing package unionfs/unionfs-fuse!
Aborted.
```

In Fedora, the command is called `funionfs`, not `unionfs` (if I understand correctly). With a symlink `unionfs -> funionfs` it errors that it cannot create the overlay:

```
Creating overlay of /home/masc/.local/share/linux-dwarf-pack and /tmp/.mount_Dwarf_6cbcqK in /tmp/lnp-QXOhKD...
Failed to mount overlay, check your install of unionfs/unionfs-fuse.
Aborted.
```

Manually running the `unionfs` command from `/opt/linux-dwarf-pack/linux-dwarf-pack.sh` results in a non-zero exit code without any explanation from unionfs what the error is (and the file system not being mounted to the `/tmp/lnp-...` directory.

I cannot get it running from the start script/`.desktop` file.

What does work: `cp -r /opt/linux-dwarf-pack ~/Applications/` and run `~/Applications/linux-dwarf-pack/startlnp.sh`. I assume this is not ideal.

I assume the [Wiki page for Fedora dependencies](https://github.com/McArcady/lnp-forge/wiki/Installing-LinuxDwarfPack-dependencies#fedorasusecentosredhat) is therefore outdated. There is no package `unionfs-fuse`. There is only `funionfs`. (Again, *if* I understand correctly)

Thank you for your time!

**Comment by McArcady** [comment]
Correct, the package name is 'funionfs', thanks for reporting.
The silent error looks like a segfault:

```
[user@fedora ~]$ funionfs  -dfo cow,uid=1000,gid=1000 /home/user/.local/share/linux-dwarf-pack/=RW:/opt/linux-dwarf-pack/ /tmp/lnp-mrDmdN/
Segmentation fault (core dumped)
[user@fedora ~]$ journalctl -f
-- Journal begins at Fri 2021-07-16 18:37:38 CEST. --
Jul 16 19:27:08 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-27316-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 16 19:27:08 fedora systemd[1]: Started Process Core Dump (PID 27316/UID 0).
Jul 16 19:27:08 fedora systemd-coredump[27317]: [🡕] Process 27315 (funionfs) of user 1000 dumped core.
                                                
                                                Stack trace of thread 27315:
                                                #0  0x00007f4b74012715 __strlen_avx2 (libc.so.6 + 0x160715)
                                                #1  0x000055dbb6eec7a5 funionfs_relist (funionfs + 0x37a5)
                                                #2  0x000055dbb6eeb92d main (funionfs + 0x292d)
                                                #3  0x00007f4b73ed9b75 __libc_start_main (libc.so.6 + 0x27b75)
                                                #4  0x000055dbb6eebabe _start (funionfs + 0x2abe)

```
still investigating...

**Comment by McArcady** [comment]
This syntax seems to work around the segfault:
`funionfs -o uid=1000,gid=1000,dirs=/home/user/.local/share/linux-dwarf-pack/=RW:/opt/linux-dwarf-pack/=RO none /tmp/lnp-mrDmdN/`

Alas! the resulting overlay does not behave like the ones created with unionfs:
- no COW option
- consequently files may not be overwritten, only created, which defeats the purpose

I do not have a solution yet...

**Comment by schemar** [comment]
OK, no worries. Thank you for trying to figure this out. Let me know if there is anything I can help with.

**Comment by McArcady** [comment]
189dbe7: fixed and tested on Fedora 34. You may try the rpm [here](https://github.com/McArcady/lnp-forge/actions/runs/1197935562)

**Comment by schemar** [comment]
Thank you @McArcady!
