### ISSUE TITLE
Error 127 after building on Arch Linux from soundsense-rs

### ISSUE THREAD

**Issue by yoonmgyg** [McArcady/lnp-forge#58]
> [INFO ]  =================================================================
[INFO ]  Building components
[INFO ]    =================================================================
[INFO ]    Building lnp-0.14a
[INFO ]    Building lnp-0.14a: done in 0.04s (at 03:23)
[INFO ]    =================================================================
[INFO ]    Credits for lnp-0.14a
[INFO ]    Credits for lnp-0.14a: done in 0.00s (at 03:23)
[INFO ]    =================================================================
[INFO ]    Building df-47_05_linux
[INFO ]      Already extracted 'df_47_05_linux'
[INFO ]    Building df-47_05_linux: done in 0.19s (at 03:23)
[INFO ]    =================================================================
[INFO ]    Credits for df-47_05_linux
[INFO ]    Credits for df-47_05_linux: done in 0.00s (at 03:23)
[INFO ]    =================================================================
[INFO ]    Building graphics-master
[INFO ]    Building graphics-master: done in 0.80s (at 03:24)
[INFO ]    =================================================================
[INFO ]    Credits for graphics-master
[INFO ]    Credits for graphics-master: done in 0.00s (at 03:24)
[INFO ]    =================================================================
[INFO ]    Building shared-master
[INFO ]    Building shared-master: done in 0.57s (at 03:24)
[INFO ]    =================================================================
[INFO ]    Credits for shared-master
[INFO ]    Credits for shared-master: done in 0.00s (at 03:24)
[INFO ]    =================================================================
[INFO ]    Building dfhack-0.47.05-r1
[INFO ]    Building dfhack-0.47.05-r1: done in 512.22s (at 11:57)
[INFO ]    =================================================================
[INFO ]    Credits for dfhack-0.47.05-r1
[INFO ]    Credits for dfhack-0.47.05-r1: done in 0.00s (at 11:57)
[INFO ]    =================================================================
[INFO ]    Building twbt-0.47.05-r1
[INFO ]    Building twbt-0.47.05-r1: done in 0.01s (at 11:57)
[INFO ]    =================================================================
[INFO ]    Credits for twbt-0.47.05-r1
[INFO ]    Credits for twbt-0.47.05-r1: done in 0.00s (at 11:57)
[INFO ]    =================================================================
[INFO ]    Building kloker-master
[INFO ]    Building kloker-master: done in 0.02s (at 11:57)
[INFO ]    =================================================================
[INFO ]    Credits for kloker-master
[INFO ]    Credits for kloker-master: done in 0.00s (at 11:57)
[INFO ]    =================================================================
[INFO ]    Building therapist-v41.2.2
[INFO ]    Building therapist-v41.2.2: done in 163.54s (at 14:40)
[INFO ]    =================================================================
[INFO ]    Credits for therapist-v41.2.2
[INFO ]    Credits for therapist-v41.2.2: done in 0.00s (at 14:40)
[INFO ]    =================================================================
[INFO ]    Building soundsensers-master
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building soundsensers-master'
[ERROR]  >>        called in step 'Building components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@261]
[ERROR]  >>        called from: do_soundsensers_build[scripts/build/soundsensers.sh@32]
[ERROR]  >>        called from: main[scripts/lnp-forge.sh@631]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '@@CT_DOCDIR@@/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 14:39.86)
make: *** [bin/lnp-forge:151: build] Error 127

Hello, I am getting Error 127 after attempting to build on Arch Linux using ` ./bin/lnp-forge build`.  When excluding sounsense-rs from the menuconfig, the package installs without issue.  I have attached the log below.

[build.log](https://github.com/McArcady/lnp-forge/files/7102580/build.log)

**Comment by McArcady** [comment]
Thanks for the report.
Try `autoreconf` instead of `autoconf` before building and it should warn you that 'cargo' is not installed

**Comment by DHMike57** [comment]
Arch packages `rust` and `webkit2gtk` are dependencies for building sounsense-rs.  Perhaps update the 'installing build dependencies' page in the wiki? Not sure about the names in other dists.

**Comment by McArcady** [comment]
fixed the Arch build deps, thanks @DHMike57
