### ISSUE TITLE
Segfault on installing in debian

### ISSUE THREAD

**Issue by sebzefrog** [McArcady/lnp-forge#61]
A clean install from todays pull (2021-12-14) dies on installing:
 Building soundsensers-master
/home/bongard/local/source/lnp-forge/lib/0.47.05-rc4/scripts/functions: line 275: 13138 Segmentation fault      "${@}" 2>&1
     13139 Done                    | CT_DoLog "${level}"
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building soundsensers-master'
[ERROR]  >>        called in step 'Building components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@261]
[ERROR]  >>        called from: do_soundsensers_build[scripts/build/soundsensers.sh@32]
[ERROR]  >>        called from: main[scripts/lnp-forge.sh@631]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '@@CT_DOCDIR@@/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 7:01.32)
make: *** [bin/lnp-forge:151: build] Error 139
[build.log](https://github.com/McArcady/lnp-forge/files/7710239/build.log)
[config.log](https://github.com/McArcady/lnp-forge/files/7710241/config.log)

**Comment by francoijs** [comment]
What happens if when building Soundsense-RS manually?
$ cd /home/bongard/local/source/lnp-forge/.build/src/soundsense-rs-master
$ cargo build --release
If it fails, there may be a problem with your 'cargo/rust' install

**Comment by sebzefrog** [comment]
Hi,

thanks for your answer. 
I tried exactly what you suggested and get the same Segmentation fault.

I'll investigate my cargo/rust install, but I didn't do anything other than load the suggested debian packets.

I'll keep you posted. If you have ideas/suggestions I'll take them gladly :)

Have a nice day
Seb
