### ISSUE TITLE
Will not start on fedora 35 

### ISSUE THREAD

**Issue by BRINGit34** [McArcady/lnp-forge#62]
I have installed the latest rpm package and whenever I try to start the game nothing happens. I have tried reinstalling and still no avail. I simply click on "play dwarf fortress" and nothing at all happens. No windows open nothing. I would be very thankful if I could get some help dealing with this as I don't understand what could be going wrong

**Comment by McArcady** [comment]
Try this:
1/ start the game from a terminal with:
`$ /opt/linux-dwarf-pack/linux-dwarf-pack.sh `
2/ in the LNP interface, click on "Play Dwarf Fortress"
3/ post here the complete log from the terminal.

**Comment by BRINGit34** [comment]
Starting LinuxDwarfPack
- configuration and game saves are stored in /home/gavinsimmons/.local/share/linux-dwarf-pack
- feedback or issues? see http://www.bay12forums.com/smf/index.php?topic=157712
- created with lnp-forge: https://github.com/McArcady/lnp-forge

Creating overlay of /home/gavinsimmons/.local/share/linux-dwarf-pack and /opt/linux-dwarf-pack in /tmp/lnp-TBsGxC...
WARNING: Could not determine installed graphics, tileset is curses_640x300.png/curses_square_16x16.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/tmp/lnp-TBsGxC/./tkgui/tkgui.py", line 557, in run_df
    launcher.run_df()
  File "/tmp/lnp-TBsGxC/core/launcher.py", line 52, in run_df
    result = run_program(executable, force, True, spawn_terminal)
  File "/tmp/lnp-TBsGxC/core/launcher.py", line 91, in run_program
    run_args = terminal.get_terminal_command([path,])
  File "/tmp/lnp-TBsGxC/core/terminal.py", line 30, in get_terminal_command
    raise Exception(
Exception: No terminal configured! Use File > Configure Terminal.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/tmp/lnp-TBsGxC/./tkgui/tkgui.py", line 562, in run_df
    message=exc_info[1].message)
AttributeError: 'Exception' object has no attribute 'message'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/tmp/lnp-TBsGxC/./tkgui/tkgui.py", line 557, in run_df
    launcher.run_df()
  File "/tmp/lnp-TBsGxC/core/launcher.py", line 52, in run_df
    result = run_program(executable, force, True, spawn_terminal)
  File "/tmp/lnp-TBsGxC/core/launcher.py", line 91, in run_program
    run_args = terminal.get_terminal_command([path,])
  File "/tmp/lnp-TBsGxC/core/terminal.py", line 30, in get_terminal_command
    raise Exception(
Exception: No terminal configured! Use File > Configure Terminal.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/tmp/lnp-TBsGxC/./tkgui/tkgui.py", line 562, in run_df
    message=exc_info[1].message)
AttributeError: 'Exception' object has no attribute 'message'

**Comment by McArcady** [comment]
Interesting: the LNP fails to show the proper error message due to an incompatibility with python3.

Anyway, you may fix the original error by going to File > Configure Terminal and select a terminal (I recommend Gnome/Cinnamon or xterm), then try again to start the game.

**Comment by BRINGit34** [comment]
That's another place I am confused as the only option I have is custom command. Nothing else shows up

**Comment by McArcady** [comment]
Try installing package 'xterm'.
If it still does not show up in the 'Terminal' menu, choose 'custom command' with this:
`xterm -e $`

**Comment by BRINGit34** [comment]
oh wow! it works! thank you very much. I appreciate it
