### ISSUE TITLE
Arch Configure Terminal issues

### ISSUE THREAD

**Issue by sdooweloc** [McArcady/lnp-forge#63]
Whenever I try to launch the appimage or the script in the tar ball I am asked to set up my terminal. I normally use alacritty so I put that asw the command but it seems to be trying to run "alacritty /usr/bin/python3" which makes no sense. I also tried konsole, xterm, and terminator with similar issues. I cannot get any terminal to work for this as it seems to be strangely trying to pass that file path into the arguments of running the terminal. Anyone have any ideas?

**Comment by McArcady** [comment]
Try installing package 'xterm'.
If it does not show up in the 'Terminal' menu, choose 'custom command' with this:
`xterm -e $`

**Comment by sdooweloc** [comment]
xterm didnt work when selecting from the menu but doing that custom command worked for both xterm and alacritty. Maybe a note could be added to the popup that the -e parameter is likely needed with your terminal command to help people know to put that. But this fixed my issue so I will be closing this now.
