### ISSUE TITLE
Arch Linux: ./bin/lnp-forge build error 1

### ISSUE THREAD

**Issue by Da-Scher** [McArcady/lnp-forge#67]
Running on Arch Linux, installed all dependencies and replaced whatever I had previously
I tried following the error and the code to see if I could solve it myself but didn't get very far. 
Attached is the build.log: [build.log](https://github.com/McArcady/lnp-forge/files/8282062/build.log)

**Comment by McArcady** [comment]
The dfhack plugin 'kloker' failed to build.
I've added an option for it in the config and it is now deactivated by default. 
See: 59c4d00.
