### ISSUE TITLE
Dwarf Therapist seg faults

### ISSUE THREAD

**Issue by godofgrunts** [McArcady/lnp-forge#68]
SHA 256 sums:

cf2d12a32a045d448b553e36b4bcbbaa6e61284f5e6a5aebf5a9b270a173ddd4  ./Dwarf_Fortress-0.47.05-r3-x86_64.AppImage

933a3db1a65678aa85d5f23036dd576f862e72fefc6bd4dc610ea03681edfeb8  ./dwarftherapist

Log attached
[dwarftherapist.log](https://github.com/McArcady/lnp-forge/files/8418419/dwarftherapist.log)

Log doesn't show the seg fault, but if dwarftherapist.sh I get the following (lines truncated to the last few lines since they line up with the log).

    2022-Apr-05 09:20:55.200 INFO	core	opening layout "/tmp/lnp-hT9dd6/share/memory_layouts/linux/v0.47.05_linux64.ini" [/home/runner/work/lnp-forge/lnp-forge/.build/src/therapist-v41.2.2/src/memorylayoutmanager.cpp:59] (reload)
    2022-Apr-05 09:20:55.201 INFO	core	adding valid layout "v0.47.05 linux64" checksum: "0x65dbcb22" SHA: "2e358941633f736ac451447fc7040575cd464ec9" [/home/runner/work/lnp-forge/lnp-forge/.build/src/therapist-v41.2.2/src/memorylayoutmanager.cpp:70] (reload)
    Segmentation fault (core dumped)

**Comment by McArcady** [comment]
does it still happens with release r5 ?

**Comment by unai-ndz** [comment]
It still happens to me, same error as @godofgrunts
