### ISSUE TITLE
Bad cursor spec

### ISSUE THREAD

**Issue by sweetyoru** [McArcady/lnp-forge#69]
i just download and unpack LinuxDwarfPack-0.47.05-r3.tar.bz2, after that, i tried to launch the game with `./startlnp.sh` and get this error:

```
WARNING: JSONConfiguration: File PyLNP.user does not exist
['Traceback (most recent call last):\n', '  File "./launch.py", line 12, in <module>\n    lnp.PyLNP()\n', '  File "/home/yoru/Downloads/LinuxDwarfPack-0.47.05-r3/core/lnp.py", line 119, in __init__\n    self.initialize_ui()\n', '  File "/home/yoru/Downloads/LinuxDwarfPack-0.47.05-r3/core/lnp.py", line 212, in initialize_ui\n    self.ui = TkGui()\n', '  File "/home/yoru/Downloads/LinuxDwarfPack-0.47.05-r3/./tkgui/tkgui.py", line 137, in __init__\n    self.root = root = Tk()\n', '  File "/usr/lib/python3.8/tkinter/__init__.py", line 2270, in __init__\n    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)\n', '_tkinter.TclError: bad cursor spec "#00ffff"\n']
```

**Comment by McArcady** [comment]
What is your Linux distribution ?
I recommend you try again with one of the rpm, deb or arch package from section "release". It may be a dependency problem.

**Comment by sweetyoru** [comment]
OS: Linux mint 20.3
I tried with the tar ball, the .deb package, and the AppImage file, none of them works.

This error come from python tinker, it can't handler custom cursor setting in ~/.Xresource. A workaround is to comment out cursor setting in Xresource and restart the machine or reload X config.

**Comment by McArcady** [comment]
for reference:
[https://stackoverflow.com/questions/45700209/bad-cursor-spec-error-after-a-simple-tkinter-tk-in-python-3-6-2](https://stackoverflow.com/questions/45700209/bad-cursor-spec-error-after-a-simple-tkinter-tk-in-python-3-6-2)
