### ISSUE TITLE
How do I restore default text tileset in LNP?

### ISSUE THREAD

**Issue by nikolas** [McArcady/lnp-forge#70]
Once I've selected a graphics tileset, I don't see any way to use the default text graphics again:

![Screenshot_2022-04-26_09-14-51](https://user-images.githubusercontent.com/59292/165308266-ecd75e2b-8cb5-4a57-87d2-08becac5feff.png)

**Comment by McArcady** [comment]
One method I've found:
in Graphics > Customize > FONT, choose "Curses_1920x900.png"
in Graphics > Customize > GRAPHICS_FONT, choose "Curses_1920x900.png"
Probably works also with other fonts like "curses_*" or "text_*"
