### ISSUE TITLE
Failure to Build Related to AppImage

### ISSUE THREAD

**Issue by JupiterSky11** [McArcady/lnp-forge#71]
I've been having loads of trouble getting this to build properly, but most of the issues are simply related to things I didn't have downloaded.  (As to why that is, I am not sure.  I ran the install script, but there is a lot more in here that I needed.)

Besides that though, I have found an error I have yet to solve.
```
[ALL  ]      [appimage/stderr] appimagetool, continuous build (commit 0880085), build 2133 built on 2020-07-09 12:25:52 UTC
[ALL  ]      [appimage/stderr] Using architecture x86_64
[ALL  ]      [appimage/stderr] Deleting pre-existing .DirIcon
[ALL  ]      [appimage/stderr] Creating .DirIcon symlink based on information from desktop file
[ALL  ]      [appimage/stderr] AppStream upstream metadata found in usr/share/metainfo/com.bay12forums.linuxdwarfpack.appdata.xml
[ERROR]      [appimage/stderr] /usr/bin/appstreamcli: symbol lookup error: /lib/x86_64-linux-gnu/libappstream.so.4: undefined symbol: g_ref_string_release
[ALL  ]      [appimage/stderr] Failed to validate AppStream information with appstreamcli
[ALL  ]      ERROR: Failed to run plugin: appimage 
```
Seems that there's a symbol lookup error, but I have no clue what that could mean or what I can do to fix it.

I'd also like to mention that building on top of a partially built results in a failed build as opposed to ignoring already built files or rewriting them, but that's just a minor complaint.

**Comment by McArcady** [comment]
Seems related to this: https://github.com/AppImage/AppImageKit/issues/856 
If I understand correctly, the recent versions of `/usr/bin/appstreamcli` (provided by our distros) do not work nicely with the libraries bundled into `linuxdeploy` (the tool used to build the Appimage, which is an Appimage itself).  
That would explain why the problem does not happen in the Github Actions CI environment (Ubuntu-18), but happens on our up-to-date distros.

**Comment by McArcady** [comment]
There is a fix (?) here, merged in Dec. 2020:  
https://github.com/AppImage/AppImageKit/commit/8bbf694455d00f48d835f56afaa1dabcd9178ba6 
Let's try with a more recent version of linuxdeploy...

**Comment by McArcady** [comment]
fix: https://github.com/McArcady/lnp-forge/commit/0a70838b8507ad50261eaaccc28bd8d0d1791f0b

**Comment by JupiterSky11** [comment]
The fix works perfectly.  Thanks for the help!
