### ISSUE TITLE
Gnome-Terminal required to use the .deb package.

### ISSUE THREAD

**Issue by ohagandavid** [McArcady/lnp-forge#72]
Frankly I don't want to install Gnome-Terminal but the package is requiring it.

```
➜  ~ sudo apt install --fix-broken
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libx264-163 mate-desktop-common
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  gnome-terminal gnome-terminal-data nautilus-extension-gnome-terminal
The following NEW packages will be installed:
  gnome-terminal gnome-terminal-data nautilus-extension-gnome-terminal
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 3,072 kB of archives.
After this operation, 11.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

I'm currently able to play the game just fine using urvxt.

**Comment by McArcady** [comment]
That's a good point but with so many users having trouble setting their terminal in PyLNP, offering 'gnome-terminal' by default helps a lot.
However I understand that non-Gnome users may find this annoying, since it will pull a bunch of gnome dependencies.
Are there a lot of APT/deb distros out there that do not use Gnome by default?

**Comment by ohagandavid** [comment]
Would a dependency on the virtual package x-terminal-emulator be acceptable? https://packages.debian.org/buster/x-terminal-emulator https://packages.ubuntu.com/jammy/x-terminal-emulator

I would think the majority of installs have one of the options installed, like my dear urxvt. :)

**Comment by McArcady** [comment]
Good idea!

**Comment by McArcady** [comment]
fixed by 336582
