### ISSUE TITLE
LNP can't launch soundsense-rs on Fedora 35

### ISSUE THREAD

**Issue by GiulioCentorame** [McArcady/lnp-forge#73]
Sorry for the previous empty issue. I noticed LNP cannot launch soundsense using the bash script on my Fedora 35. I am using the prebuilt .gz files and I have all the dependencies required, the programme works correctly while launched manually from x-term, but it doesn't work when launched from LNP launcher.

I would assume it's a problem with xterm, but it appears with both the default commands and by specifying `xterm -e $` as a custom shell. Any idea on why it could be?

Cheers

**Comment by McArcady** [comment]
What happens if your start the LNP script from a terminal with:
$ cd LinuxDwarfPack-XXXXXX/LNP/Utilities/
$ ./SoundSense-RS.sh

**Comment by GiulioCentorame** [comment]
It launches correctly, both with Gnome Terminal and xterm

**Comment by GiulioCentorame** [comment]
Sorry, I think I didn't explain it well. Soundsense launches when calling the Bash script manually, but not from the GUI.

I switched to F36 so I can see if it got fixed with the new version later today.
