### ISSUE TITLE
configure looks for qmake-qtX but on some distros its qmakeX

### ISSUE THREAD

**Issue by cmyster** [McArcady/lnp-forge#74]
These fixes configuration step for me, and I think it should be okay for the tested distros as well:

configure:5379:for ac_prog in qmake-qt5 qmake5 qmake-qt4 qmake4 qmake
configure.ac:243:AC_PATH_PROGS([QMAKE_QT],[qmake-qt5 qmake5 qmake-qt4 qmake4 qmake])

**Comment by McArcady** [comment]
Thanks! fixed in 9e26ec9
