### ISSUE TITLE
Fedora 36: cannot open shared object file libSDL_image-1.2.so.0

### ISSUE THREAD

**Issue by euclip** [McArcady/lnp-forge#79]
On Fedora 36, after installing the RPM and trying to run `/opt/linux-dwarf-pack/linux-dwarf-pack.sh` from the terminal, the LNP window opens up, but when I try to start the game itself, I get this output in the terminal:

```
Creating overlay of /home/<snip>/.local/share/linux-dwarf-pack and /opt/linux-dwarf-pack in /tmp/lnp-7tTP80...

WARNING: Could not determine installed graphics, tileset is curses_640x300.png/curses_square_16x16.png

./libs/Dwarf_Fortress: error while loading shared libraries: libSDL_image-1.2.so.0: cannot open shared object file: No such file or directory
```

**Comment by McArcady** [comment]
How has the rpm been installed ?
retry like this:
$ rpm -i linux-dwarf-pack-0.47.05_r6-1.x86_64.rpm

**Comment by McArcady** [comment]
no SDL_image?

**Comment by euclip** [comment]
Not in this case, because SDL_image was already installed, so RPM didn't complain about it, and DNF doesn't reinstall it.

However, your question made me take another look at what packages I have installed, and what I had was specifically SDL_image.i686, pulled in as a dependency of something else. I manually installed SDL_image.x86_64, specifying the arch, and then installed the linux-dwarf-pack RPM again with `dnf install ./linux-dwarf-pack-0.47.05_r6-1.x86_64.rpm` and after that the game now works correctly.

Is it possible for the RPM to specify the x86_64 arch for its dependencies?

**Comment by McArcady** [comment]
I added an option to specify the architecture when the package is built.
Not sure it will solve anything.
If you'd like to have a try, use this build: [33e3b29](https://github.com/McArcady/lnp-forge/actions/runs/2707569157)

**Comment by euclip** [comment]
Unfortunately that doesn't seem to have solved the problem. Based on my skimming the documentation for FPM, it seems there is no way to specify an architecture for dependencies, only the resulting package.

Still, at least I now know what the issue is/was and can install the right dependency by hand. Thanks!
