### ISSUE TITLE
Remove `gnome-terminal` dependency for Arch Linux/RPM package

### ISSUE THREAD

**Issue by ProspectPyxis** [McArcady/lnp-forge#86]
#72 removed the dependency on `gnome-terminal` for the `.deb` package. However, the Arch Linux and RPM packages still have a hard dependency on it. I believe not having this dependency on the arch package is even more important, as a lot of people running arch won't be using gnome by default and wouldn't want to pull in a lot of unnecessary dependencies.

**Comment by McArcady** [comment]
Good idea.
Initially it was meant to help the many people having trouble setting up the terminal in PyLNP.
At least we could replace it with xterm? (x-terminal-emulator would be a better choice, but it's not available on all distros)

**Comment by McArcady** [comment]
fixed in 7b19b24
