### ISSUE TITLE
AppImage fails to launch

### ISSUE THREAD

**Issue by ShadwDrgn** [McArcady/lnp-forge#87]
`['Traceback (most recent call last):\n', '  File "/tmp/lnp-XzZFTR/./launch.py", line 12, in <module>\n    lnp.PyLNP()\n', '  File "/tmp/lnp-XzZFTR/core/lnp.py", line 119, in __init__\n    self.initialize_ui()\n', '  File "/tmp/lnp-XzZFTR/core/lnp.py", line 211, in initialize_ui\n    from tkgui.tkgui import TkGui\n', '  File "/tmp/lnp-XzZFTR/./tkgui/tkgui.py", line 16, in <module>\n    from . import controls, binding\n', '  File "/tmp/lnp-XzZFTR/./tkgui/controls.py", line 11, in <module>\n    from . import binding\n', '  File "/tmp/lnp-XzZFTR/./tkgui/binding.py", line 12, in <module>\n    from tkinter import END\n', '  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>\n    import _tkinter # If this fails your Python may not be configured for Tk\n', 'ImportError: libtk8.6.so: cannot open shared object file: No such file or directory\n']`

looks like gkt2 library will also be needed
My understanding is that appimages should not have dependencies. Host system should not require tkinter to be installed. It shouhld be included in the appimage. :(

**Comment by ShadwDrgn** [comment]
looks like gkt2 library will also be needed

**Comment by McArcady** [comment]
Sorry for that. 
Building a complete AppImage is quite a complicated process that requires a lot of trials and errors.
Meanwhile you can use the current AppImage after installing the dependencies described [in the wiki](https://github.com/McArcady/lnp-forge/wiki/Installing-LinuxDwarfPack-dependencies).
You may also try this [flatpak](https://github.com/feng1st/dwarf-fortress-lnp-flatpak/releases/tag/v0.47.05-r7) which was recently updated with the last LinuxDwarfPack.
