### ISSUE TITLE
Updating dfhack to newest version (rc8)

### ISSUE THREAD

**Issue by magnus-ISU** [McArcady/lnp-forge#89]
Updating dfhack seemed to be straightforward, with a weird build error I was able to hack around.

I updated a line in `.config` to grab the newest github tag.

Compiling somehow failed - there was an error in compiling some C++ code.

There was an offending duplicate function called `int_to_string` in TWBT and dfhack I think.

I found TWBT and deleted the function, then reran `lnp-forge build`.

Then compilation succeeded.

Here is a binary until this is officially done: https://github.com/magnus-ISU/appimage-store

**Comment by francoijs** [comment]
here is a build:
[https://github.com/McArcady/lnp-forge/actions/runs/3610760549](https://github.com/McArcady/lnp-forge/actions/runs/3610760549)

**Comment by McArcady** [comment]
565e574
