### ISSUE TITLE
If failed due to lack of unzip...

### ISSUE THREAD

**Issue by Dreded** [McArcady/lnp-forge#91]
as per issue #90 manjaro doesnt have unzip so the build fails, once you fix that the build still fails because...

```
[ERROR]    The 'legendsbrowser-2.0.2-linux' sources were partially extracted.
[ERROR]    Please remove first:
[ERROR]     - the source dir for 'legendsbrowser-2.0.2-linux', in '/home/dreded/Games/lnp-forge/.build/src'
[ERROR]     - the file '/home/dreded/Games/lnp-forge/.build/src/.legendsbrowser-2.0.2-linux.extracting'
[ERROR]    I'll stop now to avoid any carnage...
```
when in fact all that happened was that the `legendsbrowser-2.0.2-linux` folder was created and is empty

perhpas the check for the .extracting files should also check if the folder is empty and if so continue

**Comment by McArcady** [comment]
Try `bin/lnp-forge clean build`

**Comment by Dreded** [comment]
was easy enough to just delete those two files as it says right in the error, I was thinking this might come up for other reasons so would be easy to check if the folder is empty and just ignore

I.E. 
```
#Psudo Code
if (.legendsbrowser-2.0.2-linux.extracting exists && .legendsbrowser-2.0.2-linux notEmpty`:
    displayError(partiallyExtracted)
```

**Comment by McArcady** [comment]
Thanks for the report
