### ISSUE TITLE
Error during install || Could not find library libSDL_image-1.2

### ISSUE THREAD

**Issue by apostaat** [McArcady/lnp-forge#93]
I am trying to run this command 
```$ ./configure --prefix=$PWD && make install```

it returns: 
```configure: error: Could not find library libSDL_image-1.2```

Library is installed: 
```
    brew info sdl_image 
     ==> 
    sdl_image: stable 1.2.12 (bottled), HEAD
```

Path variable is installed also. 

What am I doing wrong?

**Comment by McArcady** [comment]
The _configure_ script specifically looks for a lib named `libSDL_image-1.2.so.0`.  
Does this file exist on MacOS ?

**Comment by McArcady** [comment]
See main MacOS issue
